# Generated by Django 4.0.1 on 2022-04-10 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0013_alter_player_cup_alter_player_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_profile_options_profileincup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileincup',
            name='cup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cup_in_profile_cup', to='cup.cup'),
        ),
        migrations.AlterField(
            model_name='profileincup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_profile_cup', to=settings.AUTH_USER_MODEL),
        ),
    ]
