# Generated by Django 4.0.1 on 2022-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profileincup_cup_alter_profileincup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileincup',
            name='draws',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Remisy'),
        ),
        migrations.AddField(
            model_name='profileincup',
            name='goals_bilans',
            field=models.SmallIntegerField(default=0, verbose_name='Bilans bramek'),
        ),
        migrations.AddField(
            model_name='profileincup',
            name='goals_losted',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bramki stracone'),
        ),
        migrations.AddField(
            model_name='profileincup',
            name='goals_scored',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Bramki zdobyte'),
        ),
        migrations.AddField(
            model_name='profileincup',
            name='losses',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Porażki'),
        ),
        migrations.AddField(
            model_name='profileincup',
            name='points',
            field=models.SmallIntegerField(default=0, verbose_name='Punkty'),
        ),
        migrations.AddField(
            model_name='profileincup',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Zwycięstwa'),
        ),
    ]
