# Generated by Django 4.0.1 on 2022-03-15 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nazwa')),
                ('number_of_players', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(128)], verbose_name='Liczba graczy')),
                ('type', models.CharField(choices=[('Puchar', (('Puchar', 'Puchar'),)), ('Liga', (('1 mecz', '1 mecz'), ('2 mecze', '2 mecze')))], default='Puchar', max_length=20, verbose_name='Rodzaj')),
                ('registration', models.CharField(choices=[('Otwarta', 'Otwarta'), ('Zamknięta', 'Zamknięta')], default='Otwarta', max_length=20, verbose_name='Rejestracja')),
                ('len_rounds', models.PositiveSmallIntegerField(default=0, verbose_name='Liczba rund')),
                ('elimination_matches', models.PositiveSmallIntegerField(default=0, verbose_name='Liczba meczy eliminacyjnych')),
                ('elimination_generated', models.BooleanField(default=False, verbose_name='Wygenerowano emilimacje')),
                ('league_generated', models.BooleanField(default=False, verbose_name='Wygenerowano ligę')),
                ('finished', models.BooleanField(default=False, verbose_name='Zakończono rozgrywki')),
                ('choosing_teams', models.BooleanField(default=False, verbose_name='Wybór drużyn')),
                ('players_order', models.CharField(default='', max_length=50, verbose_name='Kolejność Graczy')),
            ],
            options={
                'verbose_name': 'Puchar',
                'verbose_name_plural': 'Puchary',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='nazwa gracza')),
                ('wins', models.PositiveSmallIntegerField(default=0, verbose_name='Zwycięstwa')),
                ('draws', models.PositiveSmallIntegerField(default=0, verbose_name='Remisy')),
                ('losses', models.PositiveSmallIntegerField(default=0, verbose_name='Porażki')),
                ('goals_scored', models.PositiveSmallIntegerField(default=0, verbose_name='Bramki zdobyte')),
                ('goals_losted', models.PositiveSmallIntegerField(default=0, verbose_name='Bramki stracone')),
                ('goals_bilans', models.SmallIntegerField(default=0, verbose_name='Bilans bramek')),
                ('points', models.SmallIntegerField(default=0, verbose_name='Punkty')),
                ('team', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Drużyna')),
                ('cup', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cup', to='cup.cup')),
            ],
            options={
                'verbose_name': 'Gracz',
                'verbose_name_plural': 'Gracze',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Nazwa rundy')),
                ('cup', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cup_in_round', to='cup.cup')),
                ('pausing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cup.player', verbose_name='Pauzuje')),
                ('players', models.ManyToManyField(blank=True, related_name='players', to='cup.Player', verbose_name='Uczestnicy')),
                ('promotion', models.ManyToManyField(blank=True, related_name='promotion_round', to='cup.Player', verbose_name='Awans')),
            ],
            options={
                'verbose_name': 'Runda',
                'verbose_name_plural': 'Rundy',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result1', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Wynik 1')),
                ('result2', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Wynik 2')),
                ('finished', models.BooleanField(default=False, verbose_name='Rozegrany')),
                ('cup', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cup_in_match', to='cup.cup')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='cup.player', verbose_name='Gracz 1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='cup.player', verbose_name='Gracz 2')),
                ('round', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='round', to='cup.round')),
            ],
            options={
                'verbose_name': 'Mecz',
                'verbose_name_plural': 'Mecze',
            },
        ),
        migrations.AddField(
            model_name='cup',
            name='actual_round',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_round', to='cup.round'),
        ),
    ]
