# Generated by Django 4.0.1 on 2022-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='match',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Runda meczy'),
        ),
    ]
