# Generated by Django 4.0.1 on 2022-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0002_round_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result1',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Wynik gospodarza'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result2',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Wynik gościa'),
        ),
    ]
