# Generated by Django 4.0.1 on 2022-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0003_alter_match_result1_alter_match_result2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='offline',
            field=models.BooleanField(default=True, verbose_name='offline?'),
        ),
    ]
