# Generated by Django 4.0.1 on 2022-03-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0005_remove_cup_offline_cup_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='declarations',
            field=models.CharField(choices=[('Otwarta', 'Otwarta'), ('Na zaproszenie', 'Na zaproszenie')], default='Otwarta', max_length=20, verbose_name='Rejestracja'),
        ),
    ]
