# Generated by Django 4.0.1 on 2022-03-26 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cup', '0006_cup_declarations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='declarations',
            field=models.CharField(choices=[('Offline', (('Ręczna', 'Ręczna'),)), ('Online', (('Otwarta', 'Otwarta'), ('Na zaproszenie', 'Na zaproszenie')))], default='Offline', max_length=20, verbose_name='Rejestracja'),
        ),
    ]
