# Generated by Django 4.0.1 on 2022-03-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0009_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Czy potwierdzony?'),
        ),
    ]
