# Generated by Django 4.0.1 on 2022-04-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0010_match_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Drużyna'),
        ),
    ]
