# Generated by Django 4.0.1 on 2022-04-09 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0011_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cup',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cup', to='cup.cup'),
        ),
    ]
