# Generated by Django 4.0.1 on 2022-04-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0012_alter_player_cup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cup', to='cup.cup'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Drużyna'),
        ),
    ]
